version: "3.5"
services:
  rabbitmq:
    image: rabbitmq:3.7.4

  mongodb:
    image: mongo
    ports:
      - 27017:27017

    command:
      - "mongod"

  redis:
    image: redis:5.0.3-alpine
    ports:
      - 6379:6379

  api:
    image: node:14
    working_dir: /usr/src/app
    environment:
      - APP_PORT=80
      - NODE_ENV=development
    command: yarn run dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:80
    depends_on:
      - mongodb

  cron:
    image: node:14
    working_dir: /usr/src/app
    environment:
      - APP_PORT=80
      - NODE_ENV=development
    command: yarn run dev-cron
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:80

  worker:
    image: node:14
    working_dir: /usr/src/app
    environment:
      - APP_PORT=80
      - NODE_ENV=development
    command: yarn run dev-worker
    volumes:
      - ./:/usr/src/app
    ports:
      - 3002:80
    depends_on:
      - rabbitmq
